fix: most other spelling errors (#490)
Expanding on #488, mostly bundles spelling fixes for:
- misc (had overlooked some)
- tracing & config-related (this commit can't stand by itself, as this
breaks a test)
- very few actual function/macro names (have not yet checked whether
they'd be breaking changes)
- test-related incl. the aforementioned file names

I'd be glad for pointers why the test-related dir/file name changes
break the test runs with:
```
Warming up the target directory
error: package ID specification `app_16375429` did not match any packages
Error: Failed to compile the test binaries
```

---------

Co-authored-by: leonqadirie <qadirie.leon@nulltree.xyz>
Co-authored-by: Luca Palmieri <20745048+LukeMathWalker@users.noreply.github.com>